apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: crossfit
resources:
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml
images:
- name: prom/prometheus
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml